# Generated by Django 4.2.7 on 2023-11-08 10:09

import uuid

import django.db.models.deletion
import events.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("end_time", models.DateTimeField()),
                ("name", models.CharField(max_length=280)),
                ("start_time", models.DateTimeField()),
                (
                    "event_type",
                    models.IntegerField(
                        choices=[(1, "CONCERT"), (2, "OFFICIAL"), (3, "OTHER")],
                        default=events.utils.EventTypes["OTHER"],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
