# Generated by Django 4.2.6 on 2023-10-26 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_attendees",
            new_name="attendees",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_descritption",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_type",
            new_name="type",
        ),
    ]
