# Generated by Django 5.0.3 on 2024-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="full_day",
            field=models.BooleanField(default=False),
        ),
    ]
