# Generated by Django 4.2.6 on 2023-10-26 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_event_attendees_event_attendees_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="type",
            new_name="event_type",
        ),
    ]
