# Generated by Django 5.0.2 on 2024-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_full_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="full_day",
            field=models.BooleanField(),
        ),
    ]
