# Generated by Django 5.1.1 on 2024-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_description_alter_event_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="full_day",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
