# Generated by Django 5.1.1 on 2024-10-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_end_time_alter_event_full_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="full_day",
            field=models.BooleanField(default=False),
        ),
    ]
