# Generated by Django 5.1.1 on 2024-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_full_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="full_day",
            field=models.BooleanField(),
        ),
    ]
