version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "monthly"
    groups:
      actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "monthly"
    groups:
      pip-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    # TODO: remove lock when typescript-eslint supports eslint v9
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
