version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "weekly"
