version: "3.9"

services:
  nisse-dev-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: nisse_dev_db
      POSTGRES_USER: nisse_dev_user
      POSTGRES_PASSWORD: nisse_dev_password
    ports:
      - "5432:5432"
    volumes:
      - nisse-dev-db-data-volume:/var/lib/postgresql/data

volumes:
  nisse-dev-db-data-volume:
