# Generated by Django 4.2.7 on 2023-11-08 10:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="end",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="start",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="engagementtype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="end",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="start",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
