# Generated by Django 4.2.7 on 2023-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_engagement_end_alter_engagement_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="trial_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
