# Generated by Django 4.2.7 on 2023-11-08 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_membership_trial_start"),
    ]

    operations = [
        migrations.RenameField(
            model_name="engagement",
            old_name="appointed",
            new_name="member",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="has_trial",
            new_name="is_trial",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="appointed",
            new_name="member",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="instrument",
            new_name="membershipType",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="trial_start",
        ),
    ]
