# Generated by Django 4.2.7 on 2023-11-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_rename_appointed_engagement_member_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="engagement",
            old_name="title",
            new_name="engagementType",
        ),
        migrations.AlterField(
            model_name="engagement",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
