# Generated by Django 4.2.7 on 2023-11-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_rename_title_engagement_engagementtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="start",
            field=models.DateField(),
        ),
    ]
