# Generated by Django 4.2.7 on 2024-01-17 19:35

import imagekit.models.fields
import members.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_alter_membership_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="avatars\\placeholderImage_400x400.png",
                upload_to=members.models.member_profile_picture_path,
            ),
        ),
    ]
