# Generated by Django 5.0.2 on 2024-02-20 16:36

import imagekit.models.fields
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_alter_member_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="active_period",
            field=models.CharField(blank=True, editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="avatars/placeholderImage_400x400.png",
                upload_to=members.models.member_profile_picture_path,
            ),
        ),
    ]
