# Generated by Django 5.0.1 on 2024-01-28 14:19

import imagekit.models.fields
import members.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_alter_member_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="avatars/placeholderImage_400x400.png",
                upload_to=members.models.member_profile_picture_path,
            ),
        ),
    ]
