# Generated by Django 5.0.2 on 2024-03-07 15:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_member_active_period_alter_member_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrasMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Lifetime"), ("U", "Unsure"), ("N", "New")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("status_date", models.DateField(blank=True, null=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="grasmembership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status__exact", ""), ("status_date__isnull", False)),
                    models.Q(
                        models.Q(("status__exact", ""), _negated=True),
                        ("status_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="grasstatus",
            ),
        ),
    ]
