# Generated by Django 5.0.2 on 2024-03-07 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_grasmembership_grasmembership_grasstatus"),
        ("members", "0008_member_active_period_alter_member_profile_picture"),
    ]

    operations = []
