# Generated by Django 5.1.1 on 2024-09-19 21:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0009_grasmembership_grasmembership_grasstatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={},
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                models.OrderBy(
                    django.db.models.functions.text.Lower("email"), descending=True
                ),
                condition=models.Q(("email__exact", ""), _negated=True),
                name="unique_or_empty",
                violation_error_message="Email must be either unique or empty.",
            ),
        ),
    ]
