# Generated by Django 5.0.3 on 2024-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_grasmembership_grasmembership_grasstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
