name: Build and test the backend

on: [push, pull_request]

jobs:
  pipenv-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    env:
      NISSE_DB_NAME: nisse_test_db
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pipenv
      - run: pipenv install --deploy --dev
      - run: pipenv run python manage.py test
      - run: pipenv run python manage.py makemigrations --check --dry-run
