name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
    env:
      # Skip `no-commit-to-branch`, since it isn't relevant in a pipeline.
      # Skip `eslint`, since it needs the frontend to be installed to work. It
      # is instead run in the node.js pipeline.
      SKIP: no-commit-to-branch,eslint
